## name: Nova Choom
## author: MurderFromMars
## license: GNU GPL
## upstream: https://github.com/MurderFromMars/Nova-Choom-Theme-Scheme

background            #000000
foreground            #77fff9
selection_background  #77fff9
selection_foreground  #000000
cursor                #77fff9

# Black, Gray, Silver, White

color0                #000000
color8                #77fff9
color7                #77fff9
color15               #77fff9

# Red

color1                #77fff9
color9                #77fff9

# Green

color2                #77fff9
color10               #77fff9

# Yellow

color3                #77fff9
color11               #77fff9

# Blue

color4                #77fff9
color12               #77fff9

# Purple

color5                #77fff9
color13               #77fff9

# Teal

color6                #77fff9
color14               #77fff9
